import Head from "next/head";
import { Calendar, momentLocalizer } from "react-big-calendar";
import moment from "moment";
import "react-big-calendar/lib/css/react-big-calendar.css";

type CalendarEvent = {
  title: string;
  start: Date;
  end: Date;
  allDay?: boolean;
  resource?: any;
};
export default function CalendarPage() {
  const events: CalendarEvent[] = [
    {
      title: "All Day Event",
      start: new Date(2022, 0, 16, 5),
      end: new Date(2022, 0, 16, 6),
    },
    // {
    //   title: "Long Event",
    //   start: new Date(2022, 1, 16),
    //   end: new Date(2022, 1, 16),
    // },
    // {
    //   title: "Repeating Event",

    //   start: new Date(2022, 1, 16, 12, 0, 0),
    //   end: new Date(2022, 1, 16, 13, 0, 0),
    // },
  ];

  const components = {
    event: (props) => {
      console.log("event", props);

      return <div>{props.title}</div>;
    },

    toolbar: (props) => {
      console.log(props);

      const { view, views, label, onView } = props;
      return (
        <div className="flex gap-x-10">
          {label}

          {views.map((item) => (
            <button
              key={item}
              onClick={() => onView(item)}
              className={`${item === view ? "font-bold" : "font-normal"}`}
            >
              {item} view
            </button>
          ))}
        </div>
      );
    },
  };

  return (
    <div>
      <Head>
        <title>Calendar | PlantIT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="pl-64 bg-homeBg min-h-screen">
        Calendar
        <Calendar
          localizer={momentLocalizer(moment)}
          events={events}
          startAccessor="start"
          endAccessor="end"
          style={{ height: 500 }}
          defaultView="day"
          components={components}
          dayPropGetter={() => {
            return {};
          }}
          eventPropGetter={() => {
            return {};
          }}
          views={{
            day: true,
            week: true,
            month: true,
          }}
          min={new Date(2021, 1, 1, 7)}
          max={new Date(2021, 1, 1, 18)}
        />
      </div>
      {/* <Calendar
                selectable
                localizer={localizer}
                defaultView="week"
                views={{
                    month: true,
                    week: WorkWeek,
                    day: true,
                }}
                popup
                events={data.appointments}
                startAccessor="start"
                endAccessor="end"
                style={{ height: '83vh' }}
                onView={handleChangeView}
                onNavigate={handleDateChange}
                onRangeChange={handleRangeChange}
                onSelectSlot={handleSelectSlot}
                onSelectEvent={handleSelectEvent}
                eventPropGetter={getEventProps}
                formats={formats}
                timeslots={4}
                step={15}
                components={components}
                
            /> */}
    </div>
  );
}
