import Head from 'next/head'
import { Calendar, momentLocalizer } from 'react-big-calendar'
import moment from 'moment'


export default function CalendarPage() {
    const localizer = momentLocalizer(moment)
    return (
        <div>
            <Head>
                <title>Calendar | PlantIT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="pl-64 bg-homeBg min-h-screen">
                Calendar
            </div>
            {/* <Calendar
                selectable
                localizer={localizer}
                defaultView="week"
                views={{
                    month: true,
                    week: WorkWeek,
                    day: true,
                }}
                popup
                events={data.appointments}
                startAccessor="start"
                endAccessor="end"
                style={{ height: '83vh' }}
                onView={handleChangeView}
                onNavigate={handleDateChange}
                onRangeChange={handleRangeChange}
                onSelectSlot={handleSelectSlot}
                onSelectEvent={handleSelectEvent}
                eventPropGetter={getEventProps}
                formats={formats}
                timeslots={4}
                step={15}
                components={components}
                min={new Date(2021, 1, 1, 7)}
                max={new Date(2021, 1, 1, 18)}
            /> */}


            <Calendar
                localizer={localizer}
                events={myEventsList}
                startAccessor="start"
                endAccessor="end"
                style={{ height: 500 }}
            />
        </div>
    )
}
