import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Chatroom: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Chatroom | CoPlan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-5xl font-bold bg-homeBg pl-64 px-4 h-screen">Chatroom</h1>
    </div>
  );
};

export default Chatroom;
