import type { NextPage } from "next";
import Head from "next/head";
import { useAuthenication } from "../utlis/store";
import Link from "next/link";

const Home: NextPage = () => {
  const { user, isAuthenticated, loading } = useAuthenication();

  console.log(loading);

  if (loading) return <h1>Loading</h1>;

  if (!isAuthenticated) return null;

  return (
    <div>
      <Head>
        <title>CoPlan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-homeBg pl-64 px-4 h-screen">
        Hello, {user.firstname}
        <Link href="/tasks" passHref>
          <div className="absolute bottom-6 right-6 cursor-pointer">
            <div className="bg-fontColor px-3 py-1 rounded-lg text-2xl font-medium text-white">Create Task</div>
          </div>
        </Link>
      </div>
    </div>
  );
};

export default Home;
