import type { NextPage } from "next";
import Head from "next/head";
import { useAuthenication } from "../utlis/store";

const Home: NextPage = () => {
  const { user, isAuthenticated, loading } = useAuthenication();

  console.log(loading);

  if (loading) return <h1>Loading</h1>;

  if (!isAuthenticated) return null;

  return (
    <div>
      <Head>
        <title>PlantIT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="bg-homeBg text-5xl font-bold pl-64 px-4 h-screen capitalize">
        Hello, {user.firstname}
      </h1>
    </div>
  );
};

export default Home;
