import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useAuthenication } from "../utlis/store";
import { toast } from "react-hot-toast";

const Login: NextPage = () => {
  const { login } = useAuthenication();

  const handleLogin = async (e) => {
    e.preventDefault();
    try {
      await login({
        email: e.target.email.value,
        password: "hey",
      });
    } catch (error: any) {
      toast.error(error.message);
    }
  };

  return (
    <div>
      <Head>
        <title>Login | CoPlan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen bg-homeBg text-fontColor">
        <p className="text-left relative text-4xl font-bold font-segoe pt-4 pl-8">
          CoPlan
        </p>

        <div className="pt-36 pb-12 grid place-items-center">
          <h1 className="text-6xl font-bold font-segoe">Get Things Done</h1>
          <h1 className="text-2xl font-semibold py-4 px-96 text-center font-comfortaa">
            A management tool to stay organized and plan ahead
          </h1>

          <form
            className="flex flex-row pt-8 pb-4 font-comfortaa"
            onSubmit={handleLogin}
            method="POST"
          >
            <input
              required
              className="bg-white rounded-l-lg placeholder:text-center p-1 focus:border-transparent focus:outline-none"
              placeholder="Enter email"
              name="email"
            />
            <div className="bg-white rounded-r-lg">
              <button className="bg-fontColor py-2 px-3 text-base text-white rounded-lg">
                Sign In
              </button>
            </div>
          </form>
          <h1 className="text-xl font-semibold py-4 px-96 text-center font-comfortaa">
            Dont have an account?
            <Link href="/signup" passHref>
              <span className="underline px-1 cursor-pointer">
                Sign Up here
              </span>
            </Link>
          </h1>
        </div>
      </div>
    </div>
  );
};

export default Login;
