import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Login: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Login | PlantIT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="h-screen bg-homeBg text-fontColor">
                <p className="text-left relative text-5xl font-semibold pt-4 pl-8 font-poppins">Coplan</p>

                <div className="pt-36 pb-12 grid place-items-center">
                    <h1 className='text-6xl font-semibold font-poppins' >Get thing done</h1>
                    <h1 className='text-2xl font-semibold py-4 px-96 text-center font-comfortaa' >A planning application for team discussion , organize work flow, and track team progress.</h1>

                    <div className='flex flex-row pt-8 pb-4 font-comfortaa'>
                        <input className='bg-white rounded-l-lg placeholder:text-center focus:border-transparent' placeholder='Enter email' />
                        <div className='bg-white rounded-r-lg'>
                            <button className='bg-fontColor py-1 px-2 text-2xl text-white rounded-lg'>Sign In</button>
                        </div>
                    </div>
                    <h1 className='text-xl font-semibold py-4 px-96 text-center font-comfortaa'>Don't have an account?<Link href='/signup' passHref ><span className='underline px-1 cursor-pointer'>Sign Up here</span></Link></h1>
                </div>

            </div>
        </div >
    )
}

export default Login
